name: Spork
version: 0.20
abstract: Slide Presentations (Only Really Kwiki)
author: Brian Ingerson <ingy@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Kwiki: 0.38
  Spoon: 0.22
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
